version: '3'

services:

  e211_notebook:
    image: phaustin/e211-notebook:latest
    build:
      context: e211book-image
      dockerfile: ./Dockerfile
    container_name: e211_notebook
    labels:
      - "traefik.enable=false"
    # ports:
    #   - "8889:8888"
    # command: ["tail", "-F","missing_file"]
    
  e350_notebook:
    image: phaustin/e350-notebook:latest
    build:
      context: e350book-image
      dockerfile: ./Dockerfile
    container_name: e350_notebook
    labels:
      - "traefik.enable=false"
    # ports:
    #   - "8889:8888"
    # command: ["tail", "-F","missing_file"]
